import './globals.css'
import { Inter } from 'next/font/google'
import Footer from './footer'
import { AppProvider } from './AppContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Zinkc',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='App'>
          <AppProvider>
            {children}
          </AppProvider>
        </div>
        <Footer/>
      </body>
    </html>
  )
}
